# -*- coding: utf-8 -*-
"""assignment_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X6VVleC_BOM4jQt8SLi3SFuMJOC1QSdt
"""

import pandas as pd
import io

df_train = pd.read_csv('Credit_train.csv')

print(df_train)

cors_train = df_train.corr()

print(cors_train)

#1. Which two variables have the largest positive correlation?
cors_train['MAXLINEUTIL']['TOTACBAL']

#2. Which two variables have the smallest positive correlation?
cors_train['MAXLINEUTIL']['DAYSDELQ']

#3. Which two variables have the smallest absolute correlation (closest to zero)?
cors_train['BUSAGE']['DAYSDELQ']

cov_train = df_train.cov()

print(cov_train)

#4. Which two variables have the largest positive covariance?
cov_train['BUSAGE']['TOTACBAL']

#5. Which two variables have the largest negative covariance?
cov_train['TOTACBAL']['DAYSDELQ']

#6. Which two variables have the smallest absolute covariance (closest to zero)?
cov_train['MAXLINEUTIL']['DAYSDELQ']

#8. What is the Chi-squared value for BUSTYPE and DEFAULT?
#9. What is the probability of Chi-squared value for BUSTYPE and DEFAULT?
from scipy import stats
df_train = df_train.dropna()

cols_chi = pd.crosstab(df_train['DEFAULT'], df_train['BUSTYPE'])
value, probablity,_ , _ = stats.chi2_contingency(cols_chi)
print(value)
print(probablity)

#10. What is the absolute Z value for DAYSDELQ and DEFAULT?
import math
a = df_train.loc[df_train['DEFAULT'] == 'Y']['DAYSDELQ']
b = df_train.loc[df_train['DEFAULT'] == 'N']['DAYSDELQ']
n1 = a.size
n2 = b.size

z = (a.mean() - b.mean()) / (math.sqrt(a.var()/n1 + b.var()/n2))
z

#11. What is the probability of Z value for TOTACBAL and DEFAULT?
import numpy as np
a = df_train.loc[df_train['DEFAULT'] == 'Y']['TOTACBAL']
b = df_train.loc[df_train['DEFAULT'] == 'N']['TOTACBAL']
n1 = a.size
n2 = b.size
z = (a.mean() - b.mean()) / (math.sqrt(a.var()/n1 + b.var()/n2))
pz = 1-(stats.norm.cdf(abs(z))-0.5)*2
pz

#12. What is the absolute Z value for BUSAGE and DEFAULT?
a = df_train.loc[df_train['DEFAULT'] == 'Y']['BUSAGE']
b = df_train.loc[df_train['DEFAULT'] == 'N']['BUSAGE']
n1 = a.size
n2 = b.size
z = (a.mean() - b.mean()) / (math.sqrt(a.var()/n1 + b.var()/n2))
abs(z)

#13. What is the absolute Z value for MAXLINEUTIL and DEFAULT?
a = df_train.loc[df_train['DEFAULT'] == 'Y']['MAXLINEUTIL']
b = df_train.loc[df_train['DEFAULT'] == 'N']['MAXLINEUTIL']
n1 = a.size
n2 = b.size
z = (a.mean() - b.mean()) / (math.sqrt(a.var()/n1 + b.var()/n2))
abs(z)

#14. Using ANOVA which numerical variable has the highest F value against BUSTYPE?
def getF(col):
  A = df_train.loc[df_train['BUSTYPE'] == 'A'][col]
  B = df_train.loc[df_train['BUSTYPE'] == 'B'][col]
  C = df_train.loc[df_train['BUSTYPE'] == 'C'][col]
  D = df_train.loc[df_train['BUSTYPE'] == 'D'][col]
  E = df_train.loc[df_train['BUSTYPE'] == 'E'][col]
  F = df_train.loc[df_train['BUSTYPE'] == 'F'][col]
  
  f, _ = stats.f_oneway(A, B, C, D, E, F)
  print('F Value of', col, ':', f)

for col in ['TOTACBAL', 'MAXLINEUTIL', 'DAYSDELQ', 'BUSAGE']:
  getF(col)