# -*- coding: utf-8 -*-
"""assignment_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eO8wSqSkZBbAJcwvAhc_id7xVrUAJYRG
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import io

df_train = pd.read_csv('Credit_train.csv')
df_test = pd.read_csv('Credit_test.csv')

print(df_train)
print(df_test)

#3. What is the probability of DEFAULT=Y in Credit_train?
default_probs_train = df_train.groupby("DEFAULT").size().div(len(df_train))

default_probs_train

#4. What is the probability of DEFAULT=N in Credit_test?
default_probs_test = df_test.groupby("DEFAULT").size().div(len(df_test))

default_probs_test

#5. Which BUSTYPE has the highest frequency in both datasets?

freq_train = df_train.groupby("BUSTYPE").size().sort_values(ascending=False)
freq_test = df_test.groupby("BUSTYPE").size().sort_values(ascending=False)

print(freq_test)
print(freq_train)

#6. Which BUSTYPE has the lowest frequency in both datasets?

freq_train = df_train.groupby("BUSTYPE").size().sort_values()
freq_test = df_test.groupby("BUSTYPE").size().sort_values()

print(freq_test)
print(freq_train)

#9. ............ Box plot.
box_plot = df_train.boxplot(column=['MAXLINEUTIL'])

#10. .......... Histogram.
hist_plot = df_train.hist(column='DAYSDELQ', bins=25)

#11. ............... Box plot.
box_plot = df_train.boxplot(column=['BUSAGE'])

#10. .......... Histogram.
hist_plot = df_train.hist(column='TOTACBAL', bins=50)